# Site settings
title: Hubert Muchalski 
email: hmuchalski@csufresno.edu
office_phone: 559-278-2711
description: > # this means to ignore newlines until "baseurl:"
  Site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hubertmuchalski
github_username:  hmuchalski

# Build settings
markdown: kramdown