# Gems
plugins: [jekyll-paginate]

# Handling Reading

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:     pretty
paginate_path: "/blog/page:num"
paginate:       3

# Setup
title:          HMLab
version:        '2020-08-19'
tagline:        'California State University, Fresno'
description:    'Organic Chemistry Research at Fresno State'
url:            https://
baseurl:        ""

author:
name:           'Hubert Muchalski'
url:            http://muchalski.net
email:          hmuchalski@csufresno.edu

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

hubs:
  cv:           /downloads/vitae.pdf
  bbmain:       https://bbl-app.learn.fresnostate.edu/webapps/login/?useCas
  bb128a:       https://bbl-app.learn.fresnostate.edu/webapps/blackboard/content/launchLink.jsp?course_id=_48640_1
