# Gems
plugins:           [jekyll-paginate]

# Handling Reading

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:     pretty
paginate_path: /page:num
paginate:       2

# Setup
title:          HMLab
version:        '2019-04-23'
tagline:        'Fresno State University'
description:    'Organic Chemistry Research at Fresno State'
url:            http://
baseurl:        ""

author:
name:           'Hubert Muchalski'
url:            http://muchalski.net
email:          hmuchalski@csufresno.edu

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

hubs:
  cv:           https://www.dropbox.com/s/kr5ix33ztfq36mf/curriculum-vitae-muchalski.pdf
  bbmain:       https://bbl-app.learn.fresnostate.edu/webapps/login/?useCas
  bb128a:       https://bbl-app.learn.fresnostate.edu/webapps/blackboard/content/launchLink.jsp?course_id=_48640_1
