# Gems
gems:           [jekyll-paginate]

# Permalinks
permalink:      pretty # Removed because Github says so

paginate:       5

# Setup
title:          Hubert Muchalski
tagline:        'Fresno State University'
description:    'The Muchalski Group'
url:            http://
baseurl:        /

author:         
name:           'Hubert Muchalski'
url:            https://muchalski.net
email:          hmuchalski@csufresno.edu

hubs:
  cv:			      https://www.dropbox.com/s/kr5ix33ztfq36mf/curriculum-vitae-muchalski.pdf
  bbmain:		    https://bbl-app.learn.fresnostate.edu/webapps/login/?useCas
  bb128a:       https://bbl-app.learn.fresnostate.edu/webapps/blackboard/content/launchLink.jsp?course_id=_48640_1

# added to change github status of the file