# Gems
 gems:           [jekyll-paginate] # removed because github

# Dependencies

kramdown:         redcarpet
highlighter:      rouge
  
# Permalinks
permalink:        pretty

# Setup
title:          Hubert Muchalski
tagline:        'Fresno State University'
description:    'The Muchalski Group'
url:            http://
baseurl:        "/"

author:         
name:           'Hubert Muchalski'
url:            https://muchalski.net
email:          hmuchalski@csufresno.edu

hubs:
  cv:			      https://www.dropbox.com/s/kr5ix33ztfq36mf/curriculum-vitae-muchalski.pdf
  bbmain:		    https://bbl-app.learn.fresnostate.edu/webapps/login/?useCas
  bb128a:       https://bbl-app.learn.fresnostate.edu/webapps/blackboard/content/launchLink.jsp?course_id=_48640_1